# We are pushing to Docker only images that are the result of a tag respecting the pattern:
#    **{branch-name}-x.y.z**
#
# Where branch-name is of the form: **{edx-version}[-{fork-name}]**
#   - **edx-version:** name of the upstream `edx-platform` version (e.g. ginkgo.1),
#   - **fork-name:** name of the specific project fork, if any (e.g. funwb).
#
# Some valid examples:
#   - dogwood.3-1.0.3
#   - dogwood.2-funmooc-17.6.1
#   - eucalyptus-funwb-2.3.19
jobs:
    - hub:
        filters:
            branches:
                ignore: /.*/
            tags:
                only: /^[a-z0-9.]*-?[a-z]*-(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)$/
